# Tenant Configuration: Premium Reseller
# This file demonstrates multi-tenant deployment configuration

routesphere:
  tenant:
    id: "reseller_premium_001"
    name: "Premium Communications Partner"
    type: "RESELLER_L1"
    parent-id: "telcobright_root"
    db-name: "reseller_premium"  # Database name from ConfigManager
    active-profile: "prod"
    active: true
    
    metadata:
      tier: "PREMIUM"
      contract-id: "CTR-2024-001"
      sla-level: "GOLD"
      max-sub-resellers: "50"
      max-end-users: "10000"
    
    profiles:
      # Production Profile for Premium Reseller
      prod:
        name: "production"
        active: true
        
        general:
          # Tenant-specific database
          database:
            type: "mysql"
            host: "db.production.local"
            port: 3306
            name: "reseller_premium_prod"
            username: "reseller_premium"
            password: "${RESELLER_PREMIUM_DB_PASSWORD}"
            url: "jdbc:mysql://db.production.local:3306/reseller_premium_prod"
            pool:
              min-size: 10
              max-size: 50
          
          # Tenant-specific Kafka configuration
          kafka:
            bootstrap-servers: "kafka.production.local:9092"
            group-id: "reseller-premium-prod"
            topics:
              cdr: "reseller-premium-cdr"
              events: "reseller-premium-events"
              billing: "reseller-premium-billing"
          
          # Shared Redis with tenant namespace
          redis:
            host: "redis.production.local"
            port: 6379
            password: "${REDIS_PASSWORD}"
            database: 1  # Different database number for tenant isolation
          
          config-manager:
            base-url: "https://config.production.local"
            tenant-endpoint: "/api/v1/tenant/reseller_premium"
        
        # Premium Reseller Socket Configurations
        sockets:
          # Premium SIP Profile - Higher limits
          sip-premium-external:
            name: "sip-premium-external"
            protocol: "SIP"
            enabled: true
            network:
              bind-address: "10.100.1.10"  # Dedicated IP for premium reseller
              bind-port: 5060
              external-ip: "203.0.113.100"  # Dedicated public IP
              external-port: 5060
              transport: "UDP,TCP,TLS"
              limits:
                max-connections: 20000  # Higher limits for premium
                max-connections-per-ip: 1000
                connection-timeout: "180s"
                rate-limit: 2000  # Higher rate limit
            security:
              auth:
                type: "digest"
                realm: "premium.routesphere.com"
                require-auth: true
              access:
                allow-networks: "0.0.0.0/0"
                require-registration: true
            settings:
              user-agent: "RouteSphere-Premium/2.0"
              max-forwards: "70"
              codec-preference: "G722,PCMU,PCMA,G729"  # Premium codecs
              
          # Premium HTTP API
          https-premium-api:
            name: "https-premium-api"
            protocol: "HTTPS"
            enabled: true
            network:
              bind-address: "10.100.1.10"
              bind-port: 8443
              limits:
                max-connections: 5000
                rate-limit: 10000  # Very high API rate limit
            settings:
              api-version: "v2"
              features: "advanced-routing,real-time-analytics,bulk-operations"
      
      # Development Profile for Premium Reseller
      dev:
        name: "development"
        active: false
        
        general:
          database:
            type: "mysql"
            host: "localhost"
            port: 3306
            name: "reseller_premium_dev"
            username: "root"
            password: "123456"
            url: "jdbc:mysql://localhost:3306/reseller_premium_dev"
          
          kafka:
            bootstrap-servers: "localhost:9092"
            group-id: "reseller-premium-dev"
          
          config-manager:
            base-url: "http://localhost:7070"
        
        sockets:
          sip-dev:
            name: "sip-premium-dev"
            protocol: "SIP"
            enabled: true
            network:
              bind-address: "127.0.0.1"
              bind-port: 15060  # Different port for dev
      
      # Mock Profile for Testing
      mock:
        name: "mock"
        active: false
        
        general:
          database:
            type: "h2"
            url: "jdbc:h2:mem:reseller_premium_test"
            username: "sa"
            password: ""
          
          kafka:
            bootstrap-servers: "mock:9092"
            group-id: "reseller-premium-mock"
        
        sockets:
          sip-mock:
            name: "sip-premium-mock"
            protocol: "SIP"
            enabled: true
            network:
              bind-address: "127.0.0.1"
              bind-port: 25060