# RouteSphere Multi-Tenant Configuration
# Lists all tenants and their profiles

tenants:
  - name: ccl
    enabled: true
    profile: dev  # Profile: dev, staging, prod, or mock

  - name: brilliant
    enabled: false
    profile: dev  # Profile: dev, staging, prod, or mock

  - name: reseller-premium
    enabled: false
    profile: dev  # Profile specified for when enabled