esl-listener:
  instance-id: ccl-prod-esl-01
  enabled: true

  # Connection settings for FreeSWITCH ESL
  connection:
    host: 103.95.96.77
    port: 8021
    password: ${ESL_PASSWORD}  # Production password from environment variable
    reconnect-interval-seconds: 3
    connection-timeout-seconds: 5

  # Tenant identification configuration
  tenant-identifier:
    # Similar to FreeSWITCH context concept - identifies which tenant/context this ESL instance belongs to
    context: ccl-prod
    tenant-id: ccl
    environment: prod

    # Channel variable patterns to identify tenant from incoming calls
    channel-patterns:
      - variable: "sip_h_X-Tenant-ID"
        pattern: "ccl"
      - variable: "context"
        pattern: "ccl-prod-.*"
      - variable: "sip_profile"
        pattern: "ccl-prod"
      - variable: "sofia_profile_name"
        pattern: "ccl-prod-profile"

  # Event subscriptions
  events:
    - CHANNEL_CREATE
    - CHANNEL_ANSWER
    - CHANNEL_HANGUP
    - CHANNEL_HANGUP_COMPLETE
    - CHANNEL_BRIDGE
    - CHANNEL_UNBRIDGE
    - CHANNEL_PROGRESS
    - CHANNEL_PROGRESS_MEDIA
    - CUSTOM
    - HEARTBEAT
    - CDR

  # Processing pipeline configuration
  pipeline:
    # Initial context for call flow analysis (like FreeSWITCH dialplan context)
    initial-context: public

    # Processors to apply for ESL events
    processors:
      - tenant-identification
      - admission-control
      - rate-limiting
      - business-rules
      - routing-decision
      - billing-pre-check
      - action-execution
      - cdr-generation

  # Load balancing configuration (for multiple FreeSWITCH instances)
  load-balancing:
    enabled: true
    strategy: round-robin
    instances:
      - host: 103.95.96.77
        port: 8021
        weight: 1
      - host: 103.95.96.78
        port: 8021
        weight: 1

  # Monitoring and health check
  monitoring:
    health-check-interval-seconds: 10
    metrics-enabled: true
    log-level: WARN
    alert-on-disconnect: true