http-listener:
  instance-id: ccl-dev-http-01
  enabled: true

  # HTTP server configuration
  server:
    host: 0.0.0.0
    port: 8080
    context-path: /api/ccl

  # Tenant identification configuration
  tenant-identifier:
    # Context similar to routing context in web applications
    context: ccl-dev
    tenant-id: ccl
    environment: dev

    # Patterns to identify tenant from HTTP requests
    identification-methods:
      - type: header
        name: X-Tenant-ID
        pattern: "ccl"
      - type: subdomain
        pattern: "ccl-dev\\..*"
      - type: path
        pattern: "/api/ccl/.*"
      - type: query-param
        name: tenant
        pattern: "ccl"

  # Request routing configuration
  routing:
    # Initial context for request processing
    initial-context: public

    # Route definitions
    routes:
      - path: /health
        method: GET
        public: true
      - path: /api/ccl/**
        methods: [GET, POST, PUT, DELETE]
        requires-auth: true

  # Processing pipeline configuration
  pipeline:
    processors:
      - tenant-identification
      - authentication
      - authorization
      - rate-limiting
      - business-rules
      - routing-decision
      - action-execution

  # Security configuration
  security:
    cors:
      enabled: true
      allowed-origins: ["http://localhost:3000"]
      allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]

    rate-limiting:
      enabled: true
      requests-per-minute: 100

  # Monitoring
  monitoring:
    metrics-enabled: true
    log-level: DEBUG
    access-log: true