# SIP Channel - WebRTC Profile
# Server mode - listens for WebRTC SIP traffic

channel:
  name: ccl-sip-webrtc
  mode: server  # Listens on IP:Port
  protocol: sip
  enabled: true

  listener:
    host: 0.0.0.0
    port: 5066
    transport: WSS  # WebSocket Secure for WebRTC

  sip:
    user-agent: RouteSphere-WebRTC/1.0
    realm: webrtc.ccl.com
    max-forwards: 70

  security:
    auth-required: true
    allowed-ips:
      - 0.0.0.0/0  # Allow from anywhere for WebRTC

  pipeline:
    name: webrtc-sip-pipeline
    async: false