# HTTP Channel - REST API Listener
# Server mode - provides REST API endpoints

channel:
  name: ccl-http-api
  mode: server  # Listens on IP:Port
  protocol: http
  enabled: false  # Active instance

  # HTTP server configuration
  listener:
    host: 0.0.0.0
    port: 8090
    context-path: /api/ccl

  # HTTP specific configuration
  http:
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    endpoints:
      - /health
      - /status
      - /calls
      - /events

  # Security configuration
  security:
    auth-type: bearer-token
    cors-enabled: false
    allowed-origins:
      - http://localhost:3000
      - https://ccl.example.com
    rate-limit: 100  # requests per minute

  # Processing pipeline
  pipeline:
    name: http-api-pipeline
    async: false
    timeout: 30000  # milliseconds

  # Monitoring
  monitoring:
    metrics-enabled: false
    access-log: true
    log-level: INFO