# ESL Channel - Primary FreeSWITCH Connection
# Client mode - connects to main FreeSWITCH server

channel:
  name: ccl-esl-primary
  mode: client  # Connects to FreeSWITCH server
  protocol: esl
  enabled: true

  connection:
    host: 192.168.1.10
    port: 8021
    password: ClueCon
    reconnect: true
    reconnect-delay: 5000  # milliseconds

  subscriptions:
    - CHANNEL_CREATE
    - CHANNEL_ANSWER
    - CHANNEL_HANGUP
    - CHANNEL_HANGUP_COMPLETE
    - CUSTOM
    - HEARTBEAT

  pipeline:
    name: call-processing-pipeline
    async: true

  monitoring:
    health-check-interval: 30
    metrics-enabled: true