esl-listener:
  instance-id: ccl-dev-esl-01
  enabled: true

  # Connection settings for FreeSWITCH ESL
  connection:
    host: localhost
    port: 8021
    password: ClueCon
    reconnect-interval-seconds: 5
    connection-timeout-seconds: 10

  # Tenant identification configuration
  tenant-identifier:
    # Similar to FreeSWITCH context concept - identifies which tenant/context this ESL instance belongs to
    context: ccl-dev
    tenant-id: ccl
    environment: dev

    # Channel variable patterns to identify tenant from incoming calls
    channel-patterns:
      - variable: "sip_h_X-Tenant-ID"
        pattern: "ccl"
      - variable: "context"
        pattern: "ccl-dev-.*"
      - variable: "sip_profile"
        pattern: "ccl-dev"

  # Event subscriptions
  events:
    - CHANNEL_CREATE
    - CHANNEL_ANSWER
    - CHANNEL_HANGUP
    - CHANNEL_HANGUP_COMPLETE
    - CUSTOM
    - HEARTBEAT

  # Processing pipeline configuration
  pipeline:
    # Initial context for call flow analysis (like FreeSWITCH dialplan context)
    initial-context: public

    # Processors to apply for ESL events
    processors:
      - tenant-identification
      - admission-control
      - business-rules
      - routing-decision
      - action-execution

  # Monitoring and health check
  monitoring:
    health-check-interval-seconds: 30
    metrics-enabled: true
    log-level: INFO