# ESL Channel - FreeSWITCH Instance 02
# Secondary/Backup FreeSWITCH ESL connection

channel:
  name: ccl-esl-freeswitch-02
  mode: client  # Connects to FreeSWITCH server
  protocol: esl
  enabled: false  # Disabled - backup instance

  # Connection settings for FreeSWITCH ESL
  connection:
    host: 103.95.96.766
    port: 8021
    password: ClueCon
    reconnect: true
    reconnect-delay: 5000  # milliseconds

  # Event subscriptions
  subscriptions:
    - CHANNEL_CREATE
    - CHANNEL_ANSWER
    - CHANNEL_HANGUP
    - CHANNEL_HANGUP_COMPLETE
    - CUSTOM
    - HEARTBEAT

  # Processing pipeline configuration
  pipeline:
    name: ccl-call-processing-pipeline
    async: true

  # Monitoring and health check
  monitoring:
    health-check-interval: 30
    metrics-enabled: false
    log-level: INFO