# ESL Channel - Main Listener
# Client mode - main FreeSWITCH ESL connection

channel:
  name: ccl-esl-main
  mode: client  # Connects to FreeSWITCH server
  protocol: esl
  enabled: true

  # Connection settings for FreeSWITCH ESL
  connection:
    host: localhost
    port: 8021
    password: ClueCon
    reconnect: true
    reconnect-delay: 5000  # milliseconds

  # Event subscriptions
  subscriptions:
    - CHANNEL_CREATE
    - CHANNEL_ANSWER
    - CHANNEL_HANGUP
    - CHANNEL_HANGUP_COMPLETE
    - CUSTOM
    - HEARTBEAT

  # Processing pipeline configuration
  pipeline:
    name: ccl-call-pipeline
    async: true

  # Tenant identification configuration
  tenant-identifier:
    context: ccl-dev
    tenant-id: ccl
    environment: dev

  # Monitoring and health check
  monitoring:
    health-check-interval: 30
    metrics-enabled: true
    log-level: INFO